// ── পশু ও অন্যান্য প্রাণী সম্পর্কিত স্বপ্ন-প্রতীক (বর্ধিত সংস্করণ) ────
// schema: symbol, aliases[], core_meaning, polarity (positive/negative/neutral), modifiers{} (ঐচ্ছিক)

export const ANIMALS = [
  { symbol: "গরু", aliases: ["গাভী", "বাছুর"], core_meaning: "সমৃদ্ধি, মাতৃসুলভ যত্ন ও জীবনের স্থিতিশীল দিকগুলোর প্রতীক।", polarity: "positive" },
  { symbol: "সাপ", aliases: ["সর্প", "কেউটে", "অজগর", "গোখরা"], core_meaning: "লুকানো ভয়, শত্রুতা বা এমন কোনো হুমকির প্রতীক যা সরাসরি দৃশ্যমান নয় কিন্তু ভেতরে ভেতরে অনুভূত হয়।", polarity: "negative" },
  { symbol: "বাঘ", aliases: ["ব্যাঘ্র"], core_meaning: "প্রবল শক্তি, তীব্র আবেগ বা এমন কোনো পরিস্থিতির প্রতীক যেখানে নিয়ন্ত্রণ হারানোর ভয় বা সাহসী মোকাবেলার প্রয়োজন।", polarity: "negative" },
  { symbol: "সিংহ", aliases: ["সিংহী"], core_meaning: "নেতৃত্ব, আত্মবিশ্বাস ও ভেতরের সহজাত শক্তির প্রতীক।", polarity: "positive" },
  { symbol: "কুকুর", aliases: [], core_meaning: "বিশ্বস্ততা, বন্ধুত্ব বা সুরক্ষার প্রতীক; আক্রমণাত্মক রূপে দেখা দিলে বিশ্বাসঘাতকতার ভয়ও নির্দেশ করতে পারে।", polarity: "positive" },
  { symbol: "বিড়াল", aliases: ["বিলাই"], core_meaning: "স্বাধীনচেতা মনোভাব, রহস্যময়তা বা এমন কোনো পরিস্থিতির প্রতীক যা পুরোপুরি নিয়ন্ত্রণে আনা যাচ্ছে না।", polarity: "neutral" },
  { symbol: "ইঁদুর", aliases: ["মুষিক"], core_meaning: "ছোট কিন্তু ক্রমাগত বিরক্তিকর দুশ্চিন্তা, সম্পদ ক্ষয় বা অলক্ষ্যে কিছু হারানোর ইঙ্গিত।", polarity: "negative" },
  { symbol: "হাতি", aliases: [], core_meaning: "বিশালতা, স্থিতিশীল শক্তি, প্রজ্ঞা বা বড় দায়িত্ব ধীরে-সুস্থে দৃঢ়ভাবে সামলানোর প্রতীক।", polarity: "positive" },
  { symbol: "ঘোড়া", aliases: ["অশ্ব"], core_meaning: "গতি, স্বাধীনতা বা জীবনের কোনো লক্ষ্যের দিকে দ্রুত এগিয়ে যাওয়ার আকাঙ্ক্ষার প্রতীক।", polarity: "positive" },
  { symbol: "মাছ", aliases: [], core_meaning: "আবেগ, অবচেতন মনের গভীরতা বা নতুন সুযোগ/সম্পদের প্রতীক।", polarity: "positive" },
  { symbol: "ছাগল", aliases: ["ভেড়া", "মেষ"], core_meaning: "সরলতা, নম্রতা বা কারো নির্দেশ/মতামত অনুসরণ করার প্রবণতার প্রতীক।", polarity: "neutral" },
  { symbol: "বানর", aliases: [], core_meaning: "চঞ্চলতা, অস্থির চিন্তা বা খেলাচ্ছলে সমস্যা এড়িয়ে যাওয়ার মানসিকতার প্রতীক।", polarity: "neutral" },
  { symbol: "খরগোশ", aliases: [], core_meaning: "সতর্কতা, দ্রুত সিদ্ধান্ত নেওয়ার প্রবণতা বা ভীরুতার প্রতীক।", polarity: "neutral" },
  { symbol: "কচ্ছপ", aliases: [], core_meaning: "ধৈর্য, দীর্ঘমেয়াদী স্থিতিশীলতা বা ধীরে কিন্তু নিশ্চিতভাবে এগিয়ে চলার মানসিকতার প্রতীক।", polarity: "positive" },
  { symbol: "ব্যাঙ", aliases: [], core_meaning: "রূপান্তর বা জীবনের একটি পর্যায় থেকে আরেকটি পর্যায়ে উত্তরণের প্রতীক।", polarity: "neutral" },
  { symbol: "মাকড়সা", aliases: [], core_meaning: "জটিল পরিস্থিতি, ধৈর্য ধরে পরিকল্পনা করার প্রবণতা বা আটকে পড়ার অনুভূতির প্রতীক।", polarity: "negative" },
  { symbol: "মৌমাছি", aliases: [], core_meaning: "পরিশ্রম, দলবদ্ধভাবে কাজ করা বা ছোট প্রচেষ্টায় বড় ফল পাওয়ার প্রতীক।", polarity: "positive" },
  { symbol: "প্রজাপতি", aliases: [], core_meaning: "রূপান্তর, স্বল্পস্থায়ী সৌন্দর্য বা জীবনের নতুন, হালকা অধ্যায়ের সূচনার প্রতীক।", polarity: "positive" },
  { symbol: "শিয়াল", aliases: [], core_meaning: "চতুরতা, কৌশলী মানসিকতা বা কারো প্রতি অবিশ্বাসের প্রতীক।", polarity: "negative" },
  { symbol: "নেকড়ে", aliases: ["ভেড়িয়া"], core_meaning: "লুকানো আগ্রাসন, দলবদ্ধ হুমকি বা কারো প্রতি সতর্ক থাকার প্রয়োজনীয়তার প্রতীক।", polarity: "negative" },
  { symbol: "ভাল্লুক", aliases: ["ভালুক"], core_meaning: "প্রবল, রক্ষণাত্মক শক্তি বা নিজের এলাকা/সীমানা রক্ষা করার প্রবৃত্তির প্রতীক।", polarity: "neutral" },
  { symbol: "হরিণ", aliases: ["মৃগ"], core_meaning: "সৌন্দর্য, কোমলতা বা সতর্কভাবে চলা এবং সহজে আঘাতপ্রাপ্ত হওয়ার সম্ভাবনার প্রতীক।", polarity: "positive" },
  { symbol: "উট", aliases: [], core_meaning: "ধৈর্য ধরে কঠিন পরিস্থিতি সহ্য করার সক্ষমতা ও দীর্ঘমেয়াদী স্থিতিস্থাপকতার প্রতীক।", polarity: "positive" },
  { symbol: "শূকর", aliases: ["বরাহ"], core_meaning: "প্রাচুর্য বা অতিরিক্ত ভোগের প্রবণতা — প্রসঙ্গ অনুযায়ী দুই দিকেই অর্থ হতে পারে।", polarity: "neutral" },
  { symbol: "কাঁকড়া", aliases: [], core_meaning: "আত্মরক্ষামূলক মনোভাব বা কঠিন বাহ্যিক আবরণের আড়ালে কোমলতা লুকিয়ে রাখার প্রতীক।", polarity: "neutral" },
  { symbol: "গিরগিটি", aliases: [], core_meaning: "পরিস্থিতি অনুযায়ী নিজেকে মানিয়ে নেওয়ার সক্ষমতা, কখনো প্রতারণা বা দ্বিচারিতার ইঙ্গিতও দিতে পারে।", polarity: "neutral" },
  { symbol: "গোসাপ", aliases: ["গুইসাপ"], core_meaning: "প্রাচীন, ধীরগতির কিন্তু স্থায়ী কোনো শক্তির প্রতীক — কখনো অস্বস্তিকর কিন্তু ক্ষতিকর নয় এমন উপস্থিতি।", polarity: "neutral" },
  { symbol: "কেঁচো", aliases: [], core_meaning: "নম্রতা, নিজেকে ছোট মনে করা বা জীবনের ভিত্তি-স্তরে থাকা কোনো প্রক্রিয়ার প্রতীক।", polarity: "neutral" },
  { symbol: "টিকটিকি", aliases: [], core_meaning: "ছোট কিন্তু ক্রমাগত অস্বস্তির প্রতীক, প্রায়ই ঘরোয়া পরিবেশের সাথে যুক্ত।", polarity: "negative" },
  { symbol: "পিঁপড়া", aliases: [], core_meaning: "পরিশ্রম, শৃঙ্খলা ও দলগতভাবে ছোট ছোট প্রচেষ্টায় বড় লক্ষ্য অর্জনের প্রতীক।", polarity: "positive" },
  { symbol: "মশা", aliases: [], core_meaning: "ছোট কিন্তু ক্রমাগত বিরক্তিকর সমস্যা যা মনোযোগ কেড়ে নেয়, যদিও নিজে বড় হুমকি নয়।", polarity: "negative" },
  { symbol: "তেলাপোকা", aliases: ["আরশোলা"], core_meaning: "এমন কোনো অপ্রীতিকর বিষয় যা বারবার ফিরে আসে, সহজে দূর হয় না।", polarity: "negative" },
  { symbol: "জোঁক", aliases: [], core_meaning: "এমন কোনো সম্পর্ক বা পরিস্থিতি যা ধীরে ধীরে শক্তি বা সম্পদ শুষে নিচ্ছে বলে অনুভূত হয়।", polarity: "negative" },
  { symbol: "শামুক", aliases: [], core_meaning: "ধীরগতি, নিজের খোলসে আশ্রয় নেওয়া বা সতর্কতার সাথে এগোনোর প্রতীক।", polarity: "neutral" },
  { symbol: "কাঠবিড়ালি", aliases: [], core_meaning: "ভবিষ্যতের জন্য সঞ্চয় করা বা প্রস্তুতিমূলক মানসিকতার প্রতীক।", polarity: "positive" },
  { symbol: "বাদুড়", aliases: [], core_meaning: "অন্ধকারে পথ চলার সক্ষমতা বা এমন কোনো ভয়ের প্রতীক যা আসলে যতটা ভয়ংকর মনে হয় ততটা নয়।", polarity: "negative" },
  { symbol: "হাঙর", aliases: [], core_meaning: "গভীর, প্রায়-অদৃশ্য কিন্তু গুরুতর হুমকির প্রতীক — মানসিক বা আর্থিক জীবনের গভীরে লুকানো ঝুঁকি।", polarity: "negative" },
  { symbol: "ডলফিন", aliases: [], core_meaning: "বুদ্ধিমত্তা, সামাজিক সংযোগ ও খেলাচ্ছলে আনন্দের প্রতীক।", polarity: "positive" },
  { symbol: "তিমি", aliases: [], core_meaning: "বিশাল, গভীর কোনো আবেগ বা অভিজ্ঞতার প্রতীক যা সহজে বোঝা যায় না কিন্তু জীবনে গভীর প্রভাব ফেলে।", polarity: "neutral" },
  { symbol: "অক্টোপাস", aliases: [], core_meaning: "একসাথে একাধিক দায়িত্ব সামলানোর মানসিকতা, বা জটিল পরিস্থিতির সাথে মানিয়ে নেওয়ার সক্ষমতা।", polarity: "neutral" },
  { symbol: "কুমির", aliases: [], core_meaning: "নীরবে অপেক্ষা করে থাকা কোনো বিপদ বা এমন কারো প্রতীক যাকে বিশ্বাস করা কঠিন।", polarity: "negative" },
  { symbol: "জেব্রা", aliases: [], core_meaning: "সাদা-কালো/দ্বৈত সত্তা বা জীবনের কোনো বিষয়ে দ্বিধাদ্বন্দ্বের প্রতীক।", polarity: "neutral" },
  { symbol: "জিরাফ", aliases: [], core_meaning: "বিস্তৃত দৃষ্টিভঙ্গি, দূরদর্শিতা বা উঁচু লক্ষ্যের দিকে তাকানোর প্রতীক।", polarity: "positive" },
  { symbol: "গণ্ডার", aliases: [], core_meaning: "কঠিন বাহ্যিক আবরণ নিয়ে আত্মরক্ষামূলক মনোভাব, কিন্তু প্রয়োজনে শক্তিশালী প্রতিক্রিয়া দেখানোর সক্ষমতা।", polarity: "neutral" },
  { symbol: "জলহস্তী", aliases: ["হিপো"], core_meaning: "বাহ্যিকভাবে শান্ত কিন্তু ভেতরে প্রবল শক্তি লুকিয়ে থাকার প্রতীক।", polarity: "neutral" },
  { symbol: "গাধা", aliases: [], core_meaning: "কঠোর পরিশ্রম, ধৈর্য বা কখনো কখনো অবমূল্যায়িত বোধ করার প্রতীক।", polarity: "neutral" },
  { symbol: "মহিষ", aliases: [], core_meaning: "কঠোর পরিশ্রম ও সহনশীলতার প্রতীক, স্থিতিশীল কিন্তু ধীর অগ্রগতির ইঙ্গিত।", polarity: "positive" },
  { symbol: "উকুন", aliases: [], core_meaning: "ছোট কিন্তু বিরক্তিকর সমস্যা যা কাছের মানুষদের মাধ্যমে ছড়াতে পারে বলে অনুভূত হয়।", polarity: "negative" },
  { symbol: "ছুঁচো", aliases: [], core_meaning: "অস্বস্তিকর কিন্তু ক্ষণস্থায়ী কোনো উপদ্রবের প্রতীক।", polarity: "negative" },
  { symbol: "শজারু", aliases: [], core_meaning: "আত্মরক্ষার জন্য নিজের চারপাশে দূরত্ব তৈরি করার প্রবণতার প্রতীক।", polarity: "neutral" },
  { symbol: "রাণী পিঁপড়া", aliases: [], core_meaning: "নেতৃত্বের দায়িত্ব ও পরিবার/দলের কেন্দ্রবিন্দু হওয়ার প্রতীক।", polarity: "positive" },
  { symbol: "সজারু বিড়াল", aliases: [], core_meaning: "স্বাধীনচেতা কিন্তু সতর্ক মনোভাবের প্রতীক।", polarity: "neutral" }
];
