// ── পাখি সম্পর্কিত স্বপ্ন-প্রতীক (বর্ধিত সংস্করণ) ──────────────
// schema: symbol, aliases[], core_meaning, polarity (positive/negative/neutral), modifiers{} (ঐচ্ছিক)

export const BIRDS = [
  { symbol: "টিয়া পাখি", aliases: ["টিয়া", "টিয়ে পাখি"], core_meaning: "যোগাযোগ, কথাবার্তা বা অন্যের মতামত/প্রভাবের প্রতীক — কখনো নিজের ভাবনার বদলে অন্যের কথা repeat করার ইঙ্গিতও দিতে পারে।", polarity: "neutral" },
  { symbol: "কাক", aliases: ["দাঁড়কাক"], core_meaning: "দুঃসংবাদ, সতর্কবার্তা বা অজানা কোনো পরিবর্তনের পূর্বাভাসের প্রতীক; মনস্তাত্ত্বিকভাবে অবচেতন মনের সতর্কতা-সংকেতও হতে পারে।", polarity: "negative" },
  { symbol: "পেঁচা", aliases: ["প্যাঁচা", "ঘুঘুপেঁচা"], core_meaning: "গোপন জ্ঞান, রাতের অন্তর্দৃষ্টি বা এমন কিছু বোঝার ইঙ্গিত যা সচেতন মনে এখনো স্পষ্ট নয়।", polarity: "neutral" },
  { symbol: "ময়ূর", aliases: ["ময়ূরী"], core_meaning: "সৌন্দর্য, আত্মবিশ্বাস ও নিজেকে প্রকাশ করার আকাঙ্ক্ষার প্রতীক; অতিরিক্ত হলে অহংকারের ইঙ্গিতও হতে পারে।", polarity: "positive" },
  { symbol: "কবুতর", aliases: ["ঘুঘু", "পায়রা"], core_meaning: "শান্তি, নির্মলতা বা কোমল সম্পর্কের প্রতীক।", polarity: "positive" },
  { symbol: "ঈগল", aliases: ["শিকারি পাখি"], core_meaning: "উচ্চাকাঙ্ক্ষা, স্বাধীনতা ও বিস্তৃত দৃষ্টিভঙ্গির প্রতীক।", polarity: "positive" },
  { symbol: "শকুন", aliases: [], core_meaning: "ক্ষয়, শেষ হয়ে যাওয়া কোনো পরিস্থিতি বা নতুন কিছু শুরুর আগে পুরনো কিছু শেষ হওয়ার প্রতীক।", polarity: "negative" },
  { symbol: "বাজপাখি", aliases: ["শিকরা"], core_meaning: "তীক্ষ্ণ দৃষ্টি, লক্ষ্যে অবিচল থাকা বা সিদ্ধান্তে দ্রুত পৌঁছানোর মানসিকতার প্রতীক।", polarity: "positive" },
  { symbol: "চড়ুই", aliases: ["চড়ুই পাখি"], core_meaning: "সরলতা, ছোট কিন্তু নিয়মিত আনন্দ বা দৈনন্দিন জীবনের ছোট প্রাপ্তির প্রতীক।", polarity: "positive" },
  { symbol: "মুরগি", aliases: ["মোরগ"], core_meaning: "গৃহস্থালি জীবন, পরিশ্রম বা নতুন দিনের সূচনার প্রতীক।", polarity: "neutral" },
  { symbol: "হাঁস", aliases: ["রাজহাঁস"], core_meaning: "স্বচ্ছতা, মার্জিত রুচি বা কঠিন পরিস্থিতিতেও ভারসাম্য বজায় রাখার সক্ষমতার প্রতীক।", polarity: "positive" },
  { symbol: "বক", aliases: [], core_meaning: "ধৈর্য, নীরব অপেক্ষা বা সুযোগের জন্য শান্তভাবে প্রতীক্ষা করার মানসিকতার প্রতীক।", polarity: "neutral" },
  { symbol: "দোয়েল", aliases: [], core_meaning: "পরিচিত পরিবেশ, নিজের শিকড় বা ঘরের প্রতি টানের প্রতীক।", polarity: "positive" },
  { symbol: "কোকিল", aliases: [], core_meaning: "লুকানো প্রতিভা, মধুর কণ্ঠ বা এমন কারো প্রতীক যে নিজের পরিচয় সহজে প্রকাশ করে না কিন্তু প্রভাব ফেলে।", polarity: "positive" },
  { symbol: "বাদুড় পাখি", aliases: [], core_meaning: "অন্ধকারে পথ চলার সক্ষমতা বা পরিবর্তনের প্রতীক।", polarity: "negative" },
  { symbol: "শালিক", aliases: [], core_meaning: "সামাজিক জীবন, সঙ্গী-নির্ভরতা বা দলবদ্ধভাবে কাজ করার মানসিকতার প্রতীক।", polarity: "positive" },
  { symbol: "চিল", aliases: [], core_meaning: "সুযোগসন্ধানী মনোভাব বা উঁচু থেকে পরিস্থিতি পর্যবেক্ষণ করার ক্ষমতার প্রতীক।", polarity: "neutral" },
  { symbol: "সারস", aliases: [], core_meaning: "নতুন সূচনা, পরিবারে নতুন সদস্যের আগমন বা ধৈর্যের প্রতীক।", polarity: "positive" },
  { symbol: "টুনটুনি", aliases: [], core_meaning: "ছোট কিন্তু প্রাণবন্ত আনন্দ, চঞ্চলতা বা ক্ষিপ্রতার প্রতীক।", polarity: "positive" },
  { symbol: "বুলবুলি", aliases: [], core_meaning: "সুরেলা যোগাযোগ, রোমান্টিক অনুভূতি বা মিষ্টি সম্পর্কের প্রতীক।", polarity: "positive" },
  { symbol: "ফিঙে", aliases: [], core_meaning: "সাহস, নিজের চেয়ে বড় শক্তির বিরুদ্ধে রুখে দাঁড়ানোর মানসিকতার প্রতীক।", polarity: "positive" },
  { symbol: "তোতা পাখি", aliases: [], core_meaning: "অনুকরণ, অন্যের কথা/মতামত পুনরাবৃত্তি করার প্রবণতার প্রতীক।", polarity: "neutral" },
  { symbol: "রাজহাঁস পাখি", aliases: [], core_meaning: "আভিজাত্য, মার্জিত রুচি বা গভীর সম্পর্কের প্রতি অনুগত থাকার প্রতীক।", polarity: "positive" },
  { symbol: "পেঙ্গুইন", aliases: [], core_meaning: "প্রতিকূল পরিবেশেও দলবদ্ধভাবে টিকে থাকার সক্ষমতার প্রতীক।", polarity: "positive" },
  { symbol: "উটপাখি", aliases: [], core_meaning: "বাস্তবতা এড়িয়ে যাওয়ার প্রবণতা বা কঠিন পরিস্থিতিতে মুখ ফিরিয়ে নেওয়ার মানসিকতার প্রতীক।", polarity: "negative" },
  { symbol: "ফ্ল্যামিঙ্গো", aliases: [], core_meaning: "স্বতন্ত্রতা, নিজস্ব রঙে নিজেকে প্রকাশ করার আত্মবিশ্বাসের প্রতীক।", polarity: "positive" },
  { symbol: "কাকাতুয়া", aliases: [], core_meaning: "উচ্ছ্বাস, উচ্চকণ্ঠে নিজের মতামত প্রকাশ করার প্রবণতার প্রতীক।", polarity: "neutral" },
  { symbol: "চকাচকি পাখি", aliases: ["চখাচখি"], core_meaning: "দাম্পত্য বা প্রেমের সম্পর্কে অবিচ্ছেদ্য বন্ধনের প্রতীক।", polarity: "positive" },
  { symbol: "মাছরাঙা", aliases: [], core_meaning: "ধৈর্য ধরে সঠিক মুহূর্তের জন্য অপেক্ষা করে দ্রুত সুযোগ কাজে লাগানোর প্রতীক।", polarity: "positive" },
  { symbol: "হুতুম প্যাঁচা", aliases: [], core_meaning: "অন্ধকারে দেখার সক্ষমতা, গভীর রাতের চিন্তাভাবনা বা লুকানো সত্য উদঘাটনের প্রতীক।", polarity: "neutral" },
  { symbol: "ঘুঘু পাখি", aliases: [], core_meaning: "শান্তি ও কোমল ভালোবাসার প্রতীক।", polarity: "positive" },
  { symbol: "বাবুই পাখি", aliases: [], core_meaning: "পরিশ্রমী দক্ষতায় নিজের আশ্রয় (ঘর/জীবন) নিজে গড়ে তোলার প্রতীক।", polarity: "positive" },
  { symbol: "গাংচিল", aliases: [], core_meaning: "স্বাধীনতা, বিস্তৃত দিগন্তে উড়ে বেড়ানোর আকাঙ্ক্ষা বা অস্থির জীবনযাত্রার প্রতীক।", polarity: "neutral" },
  { symbol: "কানিবক", aliases: [], core_meaning: "ধৈর্যের সাথে সুযোগের অপেক্ষায় থাকার প্রতীক।", polarity: "neutral" },
  { symbol: "চন্দনা পাখি", aliases: [], core_meaning: "সৌন্দর্য ও রঙিন জীবনযাত্রার প্রতি আকাঙ্ক্ষার প্রতীক।", polarity: "positive" },
  { symbol: "শামুকখোল পাখি", aliases: [], core_meaning: "কঠিন আবরণের ভেতর থেকে মূল্যবান কিছু বের করে আনার ধৈর্যের প্রতীক।", polarity: "positive" },
  { symbol: "বনমোরগ", aliases: [], core_meaning: "প্রাকৃতিক, অনিয়ন্ত্রিত জীবনীশক্তি বা স্বাধীনভাবে বেড়ে ওঠার প্রতীক।", polarity: "positive" },
  { symbol: "তিতির পাখি", aliases: [], core_meaning: "সতর্কতা ও নিজেকে লুকিয়ে রাখার প্রবণতার প্রতীক।", polarity: "neutral" },
  { symbol: "কাউয়া", aliases: [], core_meaning: "দুঃসংবাদ বা সতর্কবার্তার প্রতীক (কাক-এর সমার্থক ব্যবহার)।", polarity: "negative" },
  { symbol: "শঙ্খচিল", aliases: [], core_meaning: "উচ্চাকাঙ্ক্ষা ও দূরদর্শী নেতৃত্বের প্রতীক।", polarity: "positive" },
  { symbol: "দাঁড়কাক পাখি", aliases: [], core_meaning: "রহস্য, প্রজ্ঞা বা অজানা ভবিষ্যতের ইঙ্গিতের প্রতীক।", polarity: "neutral" },
  { symbol: "বসন্ত বাউরি", aliases: [], core_meaning: "ঋতু পরিবর্তনের মতো জীবনে নতুন পর্যায়ের সূচনার প্রতীক।", polarity: "positive" },
  { symbol: "খঞ্জনা পাখি", aliases: [], core_meaning: "চঞ্চলতা ও দ্রুত পরিবর্তনশীল মনোভাবের প্রতীক।", polarity: "neutral" },
  { symbol: "হরিয়াল পাখি", aliases: [], core_meaning: "প্রাচুর্য ও সবুজ, সতেজ জীবনের প্রতীক।", polarity: "positive" },
  { symbol: "মদনটাক পাখি", aliases: [], core_meaning: "অস্বাভাবিক বা অস্বস্তিকর কোনো উপস্থিতির প্রতীক, যা সহজে মানিয়ে নেওয়া যায় না।", polarity: "negative" }
];
